# Generated by Django 2.1.4 on 2019-01-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(max_length=64, unique=True)),
                ('account_title', models.CharField(max_length=64, null=True)),
                ('transit_number', models.PositiveIntegerField(null=True)),
                ('institution_number', models.PositiveIntegerField(null=True)),
                ('bank_name', models.CharField(max_length=64, null=True)),
                ('payment_method', models.CharField(max_length=64, null=True)),
                ('wire_fee_rate', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
            ],
            options={
                'db_table': 'client_account',
            },
        ),
        migrations.CreateModel(
            name='ClientFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ar_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('funding_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reserve_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('credit_commitee', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('purchage_sales_agreement', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('discount_fees_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('credit_insurance_total_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('reserves_withheld_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
            ],
            options={
                'db_table': 'client_fund',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
            ],
            options={
                'db_table': 'debtor',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_number', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('added_by', models.CharField(max_length=255)),
                ('verified_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('reviewing', 'reviewing'), ('approved', 'approved')], default='pending', max_length=9)),
                ('terms', models.CharField(choices=[('3', '3'), ('6', '6'), ('12', '12')], default='3', max_length=9)),
                ('is_credit_insured', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
            ],
            options={
                'db_table': 'payee',
            },
        ),
        migrations.CreateModel(
            name='PayeeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(max_length=64, unique=True)),
                ('account_title', models.CharField(max_length=64, null=True)),
                ('transit_number', models.PositiveIntegerField(null=True)),
                ('institution_number', models.PositiveIntegerField(null=True)),
                ('bank_name', models.CharField(max_length=64, null=True)),
                ('bank_account', models.CharField(max_length=64, null=True)),
                ('payee_name', models.CharField(max_length=64, null=True)),
                ('payment_method', models.CharField(max_length=64, null=True)),
                ('wire_fee_rate', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('tp_payment_fee_rate', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ticket_number', models.CharField(max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('attachment', models.FileField(null=True, upload_to='uploads/')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Payee')),
            ],
            options={
                'db_table': 'payee_account',
            },
        ),
        migrations.CreateModel(
            name='SOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('uploaded_supporting_docs', models.BooleanField(default=False)),
                ('verification_calls', models.BooleanField(default=False)),
                ('debtor_approval_emails', models.BooleanField(default=False)),
                ('estoppel_letters', models.BooleanField(default=False)),
                ('email_verification', models.BooleanField(default=False)),
                ('is_priority', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('discount_fees', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('credit_insurance_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reserves_withheld', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('additional_cash_reserve_held', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('miscellaneous_adjustment', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reason_miscellaneous_adj', models.TextField(max_length=255, null=True)),
                ('fee_adjustment', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reason_fee_adj', models.CharField(max_length=255, null=True)),
                ('additional_cash_reserve_release', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
            ],
            options={
                'db_table': 'soa',
            },
        ),
        migrations.CreateModel(
            name='SOADisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('soa_id', models.CharField(max_length=64, null=True)),
                ('client_account_id', models.CharField(max_length=64, null=True)),
                ('payee_account_id', models.CharField(max_length=64, null=True)),
                ('payment_method', models.CharField(max_length=64, null=True)),
                ('wire_fee_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tp_payment_fee_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tp_ticket_number', models.CharField(max_length=64, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
            ],
            options={
                'db_table': 'soa_disbursement',
            },
        ),
        migrations.CreateModel(
            name='SOASupportingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('notes', models.TextField(null=True)),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.SOA')),
            ],
            options={
                'db_table': 'soa_supporting_document',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='soa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.SOA'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Company'),
        ),
    ]
