# Generated by Django 2.1.4 on 2019-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soa',
            name='verification_call_notes',
            field=models.BooleanField(default=False),
        ),
    ]
