# Generated by Django 2.1.4 on 2019-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0002_soa_verification_call_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='debtor_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
