# Generated by Django 2.1.4 on 2019-01-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0003_invoice_debtor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildScheduleInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_number', models.CharField(max_length=64)),
                ('added_by', models.CharField(max_length=255)),
                ('verified_by', models.CharField(max_length=255)),
                ('terms', models.CharField(choices=[('3', '3'), ('6', '6'), ('12', '12')], default='3', max_length=9)),
                ('is_credit_insured', models.BooleanField(default=False)),
                ('debtor_name', models.CharField(max_length=64, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Client')),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.SOA')),
            ],
            options={
                'db_table': 'build_schedule_invoice',
            },
        ),
    ]
