# Generated by Django 2.1.4 on 2019-01-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0004_buildscheduleinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildscheduleinvoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='buildscheduleinvoice',
            name='soa',
        ),
        migrations.DeleteModel(
            name='BuildScheduleInvoice',
        ),
    ]
