# Generated by Django 2.1.4 on 2019-01-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0007_auto_20190130_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payeeaccount',
            name='attachment',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='soadisbursement',
            name='client_account_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='soadisbursement',
            name='payee_account_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
