# Generated by Django 2.1.4 on 2019-01-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0008_auto_20190131_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='clientaccount',
            name='wire_fee_rate',
        ),
    ]
