# Generated by Django 2.1.4 on 2019-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0010_auto_20190131_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ref_account_exec',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ref_client_key',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ref_client_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='ref_credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='ref_debtor_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='ref_debtor_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
