# Generated by Django 2.1.4 on 2019-01-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0010_auto_20190131_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soadisbursement',
            name='soa_id',
        ),
        migrations.AddField(
            model_name='soadisbursement',
            name='soa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.SOA'),
        ),
    ]
