# Generated by Django 2.1.4 on 2019-01-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0011_auto_20190131_1656'),
        ('liquidcapital', '0011_auto_20190131_1640'),
    ]

    operations = [
    ]
