# Generated by Django 2.1.4 on 2019-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0012_merge_20190131_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='soa',
            name='ar_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
