# Generated by Django 2.1.4 on 2019-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0014_auto_20190203_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='soasupportingdocument',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
