# Generated by Django 2.1.4 on 2019-02-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0015_soasupportingdocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
