# Generated by Django 2.1.4 on 2019-02-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0016_auto_20190204_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payeeaccount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payeeaccount',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='payeeaccount',
            name='payee_name',
        ),
        migrations.RemoveField(
            model_name='payeeaccount',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payeeaccount',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='payeeaccount',
            name='tp_payment_fee_rate',
        ),
        migrations.RemoveField(
            model_name='payeeaccount',
            name='wire_fee_rate',
        ),
        migrations.AlterField(
            model_name='payeeaccount',
            name='account_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payeeaccount',
            name='account_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payeeaccount',
            name='bank_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payeeaccount',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
