# Generated by Django 2.1.4 on 2019-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0017_auto_20190205_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soadisbursement',
            name='wire_fee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
