# Generated by Django 2.1.4 on 2019-02-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0018_auto_20190206_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('reviewing', 'reviewing'), ('approved', 'approved'), ('draft', 'draft')], default='pending', max_length=9),
        ),
    ]
