# Generated by Django 2.1.4 on 2019-02-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0019_auto_20190207_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('reviewing', 'reviewing'), ('approved', 'approved')], default='pending', max_length=9),
        ),
    ]
