# Generated by Django 2.1.4 on 2019-02-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0020_auto_20190207_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soa',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('submitted', 'submitted'), ('rejected', 'rejected'), ('draft', 'draft'), ('approved', 'approved')], default='pending', max_length=9),
        ),
    ]
