# Generated by Django 2.1.4 on 2019-02-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0021_auto_20190207_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayeeSupportingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('notes', models.TextField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.Payee')),
            ],
            options={
                'db_table': 'payee_supporting_document',
            },
        ),
    ]
