# Generated by Django 2.1.4 on 2019-02-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidcapital', '0022_payeesupportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeesupportingdocument',
            name='soa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidcapital.SOA'),
        ),
    ]
